### ISSUE TITLE
SwiftLog + OSLog StringInterpolation

### ISSUE THREAD

**Issue by shaps80** [apple/swift-log#208]
I just wanted to share a library I've made that adds string interpolation to the SwiftLog implementation.

Unfortunately I couldn't see a way to do this without copy/pasting the code (would love any ideas on improving this) but I have kept the code almost entirely untouched and the copyright notices in tact of course.

I am not submitting a PR as I'm fairly certain this is pretty Apple platforms specific and wouldn't make sense in other environments.

But in case its useful to anyone else, here it is: https://github.com/shaps80/Logging

I've started adding tests as well and the implementation is not yet complete, but any feedback/issues/contributions are certainly welcome.

![shaps_2021-Sep-20](https://user-images.githubusercontent.com/251310/134022381-22406284-1f91-4da3-8a3d-95cf3b9625f1.png)

**Comment by shaps80** [comment]
@ShivaHuang / @ktoso If you're able to take a look, I'd love to know if this is something that might make sense in the actual library itself. I'm guessing not if it's not already been done. There are likely other platform specific issues I'm unaware of. But I thought I'd ask the question in case this is something that might be worthy of a more complete PR?

Thanks.

**Comment by weissi** [comment]
@shaps80 this cannot be added to SwiftLog without changing API. Also, SwiftLog encourages you to add variable data in the metadata section. For example:

```
logger.debug("Found results", metadata["count": "\(results.count)"])
```

If you need log privacy, then I would encourage this strategy in your logging backend:
- by default print only the `message` and the metadata _keys_, hide all metadata _values_ (because they may contain private data)
- for certain fields that you know have no private info, show them. Basically have an allow list of keys you know are fine to print, redact all other metadata values
- make sure that only static data is provided in the actual log message

OSLog's API assumes that every piece of software can always tell whether something is private or not. But that's difficult to tell. For example in most cases a URL for a HTTP library is not private data. But in certain cases it may be. That's why I'd encourage you to use the above way.

The reason that SwiftLog encourages to put all variable data in the metadata has a couple of reasons:
- privacy controls (as described above)
- filtering in log aggregation systems, you can just filter by the log message

**Comment by shaps80** [comment]
Interesting, I guess the ergonomics for an API using that approach are less than ideal though. Hence why I thought the OSLog approach was more appropriate, particularly for apps.

Still, thank you for clarifying this really helped and I'll do some more thinking on your feedback above. Really appreciate you taking the time to respond 👍
