### ISSUE TITLE
Unable to log stored string

### ISSUE THREAD

**Issue by MrLotU** [apple/swift-log#63]
When handling errors, I would like to be able to log `error.localizedDescription`.

### Expected behavior
`logger.error(_:)` takes in the string and logs it

### Actual behavior
Error: 
```
Cannot convert value of type 'String' to expected argument type 'Logger.Message'
```

### Steps to reproduce

1. Create a throwing function
2. Invoke throwing function
3. Add generic catch block
4. Try to invoke `Logger.error(_:)` with `error.localizedDescription`
5. Observe

### If possible, minimal yet complete reproducer code (or URL to code)

[GH Link to line/project I was working on when I found out](https://github.com/MrLotU/SwiftHooks/blob/master/Sources/SwiftHooks/Commands/SwiftHooks%2BCommands.swift#L61)

### SwiftLog version/commit hash
From `Package.resolved`:
```
"revision": "a64dd7dafc06bcecc43ec4dff0d71ef797247456"
"version": "1.0.0"
```

### Swift & OS version (output of `swift --version && uname -a`)
```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.5.0
Darwin LotU-MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

**Comment by MrLotU** [comment]
Temporary workaround for anyone wondering:
```swift
logger.error("\(error.localizedDescription)")
```

**Comment by weissi** [comment]
@MrLotU this is by design and not a bug. Your "workaround" is exactly the right thing to do. The reason we don't use `String` directly is twofold:

1. being able to unlock future performance improvements as described [here](https://forums.swift.org/t/custom-string-interpolation-and-compile-time-interpretation-applied-to-logging/18799)
2. more API parity to what's proposed in the link above which will lead to better compatibility between SwiftLog and os_log

**Comment by MrLotU** [comment]
Ah, didn't know that. Thanks for the explanation!
