### ISSUE TITLE
Lock is internal

### ISSUE THREAD

**Issue by dnwz** [apple/swift-log#82]
I'd like to use `Lock` in a custom LogHandler implementation but am unable to because `Lock` is declared as `internal` in `Locks.swift`. Was `Lock` intended to be used like this?

### Expected behavior

Under "Special cases" in the API docs [here](https://apple.github.io/swift-log/docs/current/Logging/Protocols/LogHandler.html), the example implementation `LogHandlerWithGlobalLogLevelOverride` has a property `overrideLock = Lock()`.

### Actual behavior

This is not possible if the custom LogHandler implementation (e.g. `LogHandlerWithGlobalLogLevelOverride`) is defined in another module as `Lock` is internal and not visible there.

### SwiftLog version/commit hash

`version: 0.0.0`

### Swift & OS version (output of `swift --version && uname -a`)

`Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.6.0`

**Comment by ktoso** [comment]
It is internal on purpose; swift-log should not expose any more types than the core logging interface things. 

The situation with logs and concurrency primitives in Swift currently is a bit weird, since no such types exist in Swifts stdlib, however in order to avoid many libraries linking to someone's other's lock types such types are always internal in these libraries -- so that when a Lock type lands in standard library we can remove it here without breaking anyone's code.

You can copy the locks file to your own project if you want to use this Lock or you can use some other Lock structure (NSLock, or your own); https://github.com/apple/swift-log/blob/master/Sources/Logging/Locks.swift

**Comment by ktoso** [comment]
I do realize it is a bit weird that the docs example assumes the existence of the `Lock` type though...
Not sure what to do about this, it should definitely not be an example without locking as then people would be under impression that no locking is needed...

Perhaps we can add a comment next to the `LogHandlerWithGlobalLogLevelOverride`'s Lock that "bring your own"?

**Comment by ktoso** [comment]
WDYT, @tomerd @weissi should we do something here?
Perhaps the minimal 

> Perhaps we can add a comment next to the LogHandlerWithGlobalLogLevelOverride's Lock that "bring your own"?

change would be good enough to resolve this ticket?

**Comment by weissi** [comment]
@ktoso maybe we just use `NSLock` from Foundation?
